### ISSUE TITLE
__padXXX в структурах

### ISSUE THREAD

**Issue by nikita-yfh** [sergey-raevskiy/xlay#1]
Я решил делать OpenSource аналог SprintLayout, и я не понимаю, что обозначают переменные __padX и _padX_X в структурах. Глядел hex редактором, соответствий к значениям SL не обнаружил, хотя изменяются вместе с другими полями. Кто-нибудь может подсказать?

**Comment by sergey-raevskiy** [comment]
__padX это поля для выравнивания, чтобы общий размер структуры в байтах был правильный. при этом их назначение (пока) понять не удалось. вполне может быть, что значительная часть этих полей и вовсе не используется (reserved), а значения их изменяются потому, что разработчики sl не озаботились их инициализацией и записывают в файл мусор

**Comment by nikita-yfh** [comment]
В таком случае, если изменять эти значения в hex редакторе, на плате не должно быть изменений

**Comment by nikita-yfh** [comment]
Нашел применение __pad3[16]. Это четыре 32bit числа, которые обозначают сдвиг изображений (x1,x2,y1,y2). unk1 и unk2 это dpi этих двух изображений. А вот unk3 и unk4 видимо мусор.

**Comment by sergey-raevskiy** [comment]
patches welcome!
